version: "3.8"
services:

    laravel-docker:
        container_name: laravel-docker
        build: .
        volumes:
            - .:/var/www/html
        ports:
            - 9000:80
        links:
            - mariadb
    mariadb:
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: Intern2023
        volumes:
            - ./docker/mysql:/var/lib/mysql
        ports:
            - 3306:3306
    worker:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
        depends_on:
            - mariadb
        command: php artisan queue:work
